### PR TITLE
Updated to working version of left-pad

### PR DESCRIPTION
**Pull request by camwest**

### CODE REVIEW

**Comment by mridgway** [comment]
Resolves #1

**Comment by tomesposito** [comment]
+1

**Comment by macklevine** [comment]
+1

Something I'm maintaining won't build until this is addressed; gotta hack fast

**Comment by doowb** [comment]
perhaps conider using [pad-left](https://www.npmjs.com/package/pad-left) instead. it's not having issues on npm and it's orders of magnitude faster because it uses [repeat-string](https://www.npmjs.com/package/repeat-string)

**Comment by michaelficarra** [comment]
It's a bad idea to use `^` and `0.x` together.

**Comment by taion** [comment]
I'd amend @michaelficarra's point to say that using `^0.0.9` makes no sense, since that only matches `0.0.9` exactly.

It'd make the most sense to use a version that actually has correct semver semantics, or else switch to the faster pad-left entirely, per @doowb.

**Pull request closed without merging**
